[base]
pidfile = "/tmp/api.pid"
socket_type = "tcp"
unix_socket = "/tmp/goupload.sock"
tcp_socket = "127.0.0.1:8080"

[upload]
path = "/var/www/"
mime_types = "image/jpeg;image/png;image/gif;image/x-icon;image/pict"

[http]
upload_url = "/api/upload"
status_url = "/api/status"
base_url = "http://somename.com"
index_page = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CDN upload tool</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<div class="container">
<form method="post" enctype="multipart/form-data">
<h2 align="center">Upload new files</h2><br>
<div class="form-group row">
<label for="files" class="col-sm-2 col-form-label">Select images:</label>
<div class="col-sm-10">
<input type="file" class="form-control" id="files" required="" name="file" multiple="">
</div>
</div>
<div class="form-group row">
<label for="file_path" class="col-sm-2 col-form-label">Images path (optional)</label>
<div class="col-sm-10">
<input type="text" class="form-control" id="file_path" name="path">
</div>
</div>
<div class="form-group row">
<div class="offset-sm-2 col-sm-10">
<button type="submit" class="btn btn-success">Upload</button>
</div>
</div>
<div class="form-group row">
<div class="offset-sm-2 col-sm-10">
<button type="reset" class="btn btn-danger">Reset form</button>
</div>
</div>
</form>
</div>
</body>
</html>"""